version: "3"
services:
  app:
    container_name: openlist-strm
    image: 'jacksaoding/openlist-strm:latest'
    network_mode: "host"
    environment:
      TZ: Asia/Shanghai
      openlistServerUrl: http://192.168.1.2:5244
      openlistServerToken: xxx
      openlistScanPath: /阿里云分享/电影
    volumes:
      - /volume1/docker/openlist-strm/data:/data